### ISSUE TITLE
Auto-Indent does not indent single-line blocks (Java) 

### ISSUE THREAD

**Issue by batjko** [atom/language-java#10]
Hi there, 

This is probably a long-existing issue, but it's the first time I use auto-indent and I suspect it's the language-java scheme that determines how auto-indent behaves in java files? If not, let me know.

This should illustrate the difference between blocks with brackets and those without:
![autoindent2](https://cloud.githubusercontent.com/assets/7287076/5919387/3ef8686c-a62b-11e4-8530-f8141a43035a.gif)

Cheerio.

**Comment by muppetjones** [comment]
The indent problem is atom-wide (since 0.192 as far as I can tell): [here](https://github.com/atom/atom/issues/6655).

**Comment by sadikovi** [comment]
Not an issue.
