### ISSUE TITLE
Syntax highlighting confused.

### ISSUE THREAD

**Issue by KaiShoya** [atom/language-java#106]
```java
String str1 = "('" + new Date() + "')");
```
![screen shot 2017-08-10 at 15 31 40](https://user-images.githubusercontent.com/5924971/29157308-465be184-7de1-11e7-9bcf-076ecf3cac40.png)
![screen shot 2017-08-10 at 15 31 49](https://user-images.githubusercontent.com/5924971/29157314-49e686f6-7de1-11e7-8c76-22635ea84d9e.png)

**Comment by sadikovi** [comment]
This should be fixed in master branch and v0.27.3 (tested locally those branches).

<img width="402" alt="screen" src="https://user-images.githubusercontent.com/7788766/29159005-3e1729f0-7e01-11e7-9d6e-fd4490fa70f1.png">

**Comment by Ben3eeE** [comment]
Thanks for reporting this!

This has already been fixed in `v0.27.3`. It is currently scheduled for release when Atom 1.21 reaches Stable.

---

Thanks @sadikovi :bowing_man:
