### ISSUE TITLE
Java syntax highlighting breaks on quote-parentheses combo

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#107]
_From @oakad on August 12, 2017 9:54_

Version: 1.14.2, Linux

The following line `IGNORE_SPACE(8, "ignore spaces before '('")`, seen inside enum declaration breaks highlighting, while being a perfectly valid Java.

_Copied from original issue: Microsoft/vscode#32367_

**Comment by aeschli** [comment]
_From @weinand on August 12, 2017 16:47_

Is this reproducible when running VS Code with extensions disabled?

**Comment by aeschli** [comment]
_From @oakad on August 13, 2017 9:53_

Yes, disabling all extensions via command palette makes no difference. Feels like regex error in the highlighting profile to me.

**Comment by mrerhuo** [comment]
how to setting in vscode?
