### ISSUE TITLE
java syntax highlight break on annotation interface

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#109]
_From @tnclong on September 9, 2017 1:2_

- VSCode Version:

1.16.0

- OS Version:

macOS 10.12.3

- Steps to Reproduce:

<img width="756" alt="screen shot 2017-09-09 at 8 55 40 am" src="https://user-images.githubusercontent.com/10040765/30235628-16088118-953d-11e7-92f7-37eea775569f.png">

- Reproduces without extensions

Yes

_Copied from original issue: Microsoft/vscode#34058_

**Comment by 50Wliu** [comment]
No repro.
![java-interface-default-annotation](https://user-images.githubusercontent.com/2766036/32216296-f5e5f972-be24-11e7-87d5-aa885bcdff9c.png)
