### ISSUE TITLE
Syntax breaks through asciidoc code block.

### ISSUE THREAD

**Issue by mitm001** [atom/language-java#111]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When using asciidoc, if you do not add closing bracket to a piece of code in a code block, it will bleed past the code block closing statement of ---- and into the rest of the document. Breaking the entire document code highlighting past this point.

See this discussion on Atom boards,

 https://discuss.atom.io/t/mass-red-highlight-issue/41329/15

### Steps to Reproduce

1. Create a asciidoc code block with missing closing bracket.
//[source, java]
//----
//public MyClass implements Foo {
//----
2. see link for images and explanation of the problem in detail.

**Expected behavior:** [What you expect to happen]
There should be no need to close off any statement in a code block. Its not expected to be compliable.

**Actual behavior:** [What actually happens]
Breaks past closing statement and renders document unusable for anything other than plain text editing.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom ver 1.21 x64
Win 7 home premium service pack 1

### Additional Information

Turning off the Language-java package fixes the issue.

**Comment by mitm001** [comment]
See bug report on Atom forum.

https://discuss.atom.io/t/mass-red-highlight-issue/41329/15

**Comment by 50Wliu** [comment]
This is a larger issue documented in atom/first-mate#83.
