### ISSUE TITLE
Syntax highlighting is not working with comment

### ISSUE THREAD

**Issue by snjeza** [atom/language-java#114]
VS Code 1.18

The VS Code master:

![syntax2](https://user-images.githubusercontent.com/388609/32010429-1a1a7088-b9b2-11e7-91de-d627d6872474.png)
The VS Code master with https://github.com/Microsoft/vscode/pull/36786:

![syntax3](https://user-images.githubusercontent.com/388609/32010470-336dae6a-b9b2-11e7-9606-f425faa12ecb.png)

Test2.java
```
package pckg;

public class Test2 
implements Int {
    private JPanel plottingSurface = new JPanel() /* {
        @Override
        public Dimension getPreferredSize() {
            return new Dimension(400, 300);
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
        }
    }*/;

    public static <M extends Map<Integer, String>> 
boolean TestGet(Supplier<M> c) {
 //TODO write unit test for get
 //Setup
 Map<Integer, String> map = c.get();
 return false;
}
}
```
Copied from https://github.com/Microsoft/vscode/pull/36786#issuecomment-339389126

See https://github.com/Microsoft/vscode/issues/36688, https://github.com/redhat-developer/vscode-java/issues/338 and https://github.com/Microsoft/vscode/pull/36786

**Comment by sadikovi** [comment]
Interesting. Several observations:
1. Inline comments work okay, if function definition is on the same line, e.g.
Works:
```java
public static <M extends Map<Integer, String>> boolean TestGet(Supplier<M> c) {
  // works
}
```
Does not work:
```java
public static <M extends Map<Integer, String>> 
boolean TestGet(Supplier<M> c) {
  // does not work
}
```

2. Multi-line comments work if they do not follow `new` keyword.
Works:
```java
private JPanel plottingSurface = /*new JPanel() {
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(400, 300);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    }
}*/;
```
Does not work:
```java
private JPanel plottingSurface = new /*JPanel() {
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(400, 300);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    }
}*/;
```
I will have a closer look today.

**Comment by 50Wliu** [comment]
@sadikovi thanks for jumping so quickly on this.  I already have a fix for the new comments and am looking into the second method issue now.

**Comment by sadikovi** [comment]
Nice! Thanks @50Wliu! That is really good that you have a fix for it.
I was just doing routine morning check:)

**Comment by 50Wliu** [comment]
I'm going to say the multiline method signature is a `wontfix` due to the conflicting `member-variables` match.

**Comment by snjeza** [comment]
The following patch fixes member-variables:

```
diff --git a/grammars/java.cson b/grammars/java.cson
index 5975c1d..b248160 100644
--- a/grammars/java.cson
+++ b/grammars/java.cson
@@ -1254,4 +1254,7 @@
       {
         'include': '#variables'
       }
+      {
+        'include': '#comments'
+      }
     ]
```

**Comment by tristan957-expero** [comment]
Is this issue related to:
```java
catch (IOException /*| AWSNullStreamException*/ e)
```

In VSCode, current stable, the comment is not highlighted like a comment.

**Comment by sadikovi** [comment]
@tristan957-expero Nah, does not look like it, but I might be wrong here.
I managed to fix it with following diff:

```diff
diff --git a/grammars/java.cson b/grammars/java.cson
index 55c3967..0c78f04 100644
--- a/grammars/java.cson
+++ b/grammars/java.cson
@@ -577,6 +577,9 @@
         'name': 'meta.catch.java'
         'patterns': [
           {
+            'include': '#comments'
+          }
+          {
             'begin': '\\('
             'beginCaptures':
               '0':
@@ -590,6 +593,9 @@
               {
                 'include': '#parameters'
               }
+              {
+                'include': '#comments'
+              }
             ]
           }
           {
@@ -1259,6 +1265,9 @@
         'include': '#variables'
       }
       {
+        'include': '#comments'
+      }
+      {
         'include': '#primitive-arrays'
       }
       {
```

I think we should open a PR to fix this!

**Comment by sadikovi** [comment]
@50Wliu should we close this issue? You fixed the main problem with highlighting and we patched separate issue raised in comments. Or is there anything else we need to do? Thanks!

**Comment by 50Wliu** [comment]
Yeah, I'm in favor of closing this issue.  For people who are still experiencing problems with comments when Atom 1.25 is released, please create new issues so that we can specifically target them :).
