### ISSUE TITLE
Improper syntax highlighting for Java package name

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#117]
_From @tristan957-expero on December 19, 2017 18:52_

- VSCode Version: 1.19
- OS Version: MacOS 10.13

Steps to Reproduce:
1. Create Java file
2. write `package com.helloWorld;`

The W will not have the same syntax highlighting

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#40530_

**Comment by 50Wliu** [comment]
From https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html:
> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.

I am open to tokenizing uppercase letters as deprecated, but otherwise I think this will be a wontfix.

**Comment by tristan957** [comment]
It's a naming **convention** though. That doesn't mean Java doesn't allow it. I could understand if it was the first letter that was capitalized but it's a character in the middle.

**Comment by sadikovi** [comment]
@50Wliu Should we fix this? I am happy to have a look, if you want.

**Comment by 50Wliu** [comment]
I suppose this goes back to https://github.com/atom/design-decisions/pull/1.  Personally I think we should enforce the convention.

**Comment by tristan957** [comment]
I don't want to come off as rude, but why should a language enforce a *convention*. There are many conventions that people don't follow when programming. Think of the entirety of of PEP8. Why should a syntax highlighter expect me to follow every convention of a language? The equivalent of this argument in Python would be not highlighting a function definition because it isn't 2 lines under the import statements.

**Comment by tristan957** [comment]
I can understand not highlighting improper class names that don't start with capital letters because the Java compiler will yell at you. The Java compiler will not criticize my decision to camel case my package names

**Comment by 50Wliu** [comment]
Not to worry; you're not coming off as rude at all.  And I don't want to undermine your argument, but language-python does set [some defaults](https://github.com/atom/language-python/issues/62#issuecomment-102582790) to what PEP8 recommends.

That said, I think it's long overdue that we revisit atom/design-decisions#1 and make a final decision for or against.  Perhaps this _should_ be for linters to catch and not expressed in the language.  I'll see if I can get some discussion going around that again.

**Comment by 50Wliu** [comment]
Hi there.  Quick update: we have decided that we are going to keep this invalid highlighting, but change the scope that it can more easily be styled out if you so desire without affecting other invalid scopes.  In Atom, you can do this through the `Application: Open Your Stylesheet` command.  I'm not sure if there's an equivalent way to do it in VSCode.

**Comment by tristan957** [comment]
Well I can't say that I agree at all :(. Truly unfortunate

**Comment by 50Wliu** [comment]
The new scope name from here on out is `invalid.deprecated.package_name_not_lowercase.java`.
