### ISSUE TITLE
Syntax highlighting treats `/**/` as the start of a JavaDoc

### ISSUE THREAD

**Issue by beautron7** [atom/language-java#120]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the Java language, if a multiline comment has no inner content, the language assumes the comment never closed.

### Steps to Reproduce

Paste the following code into atom.

```java
/**/  int nohilighting  = 1;
/**/  int yeshilighting = 1;
/**/  int nohilighting  = 1;
/**/  int yeshilighting = 1;

/***/ int yeshilighting = 1;
/***/ int yeshilighting = 1;
/***/ int yeshilighting = 1;
/***/ int yeshilighting = 1;
/***/ int yeshilighting = 1;
/**/  int nohilighting  = 1;
/**/  int yeshilighting = 1;
```

Alternatively, just put `/**/` at the beginning of a file.

**Expected behavior:**

Something similar to the above syntax hilighting

**Actual behavior:**

![image](https://user-images.githubusercontent.com/17390859/34579181-8c9d5ec2-f14d-11e7-96b9-b046df79ed41.png)

**Reproduces how often:**

Always

### Versions
```
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment]
Oh, it's seeing it as Javadoc.

**Comment by sadikovi** [comment]
Yes, it is a bug, apologies for that - I should have tested this situation with empty comments.
Exists in current master branch.

Here is the patch to fix it:
```diff
diff --git a/grammars/java.cson b/grammars/java.cson
index 33b209b..55c3967 100644
--- a/grammars/java.cson
+++ b/grammars/java.cson
@@ -477,7 +477,7 @@
     ]
   'comments-javadoc':
     'patterns': [
-      'begin': '^\\s*/\\*\\*'
+      'begin': '^\\s*/\\*\\*(?!/)'
       'beginCaptures':
         '0':
           'name': 'punctuation.definition.comment.java'
```

Passes all tests with this:
```
.................................................

Finished in 1.477 seconds
49 tests, 797 assertions, 0 failures, 0 skipped

Tests passed
```

@50Wliu @beautron7 If you are good with patch, I can open PR to fix it ASAP.

**Comment by 50Wliu** [comment]
Sounds great to me @sadikovi.
