### ISSUE TITLE
Java syntax highlighting errors

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#127]
The built-in Java Textmate grammar has several highlighting inconsistencies/errors.
atom/language-java (https://github.com/atom/language-java/commit/7a42895fead16e2c39c6667fc9e7ce0f7f922ac4)

- Variables/constants starting with a capital letter are scoped as `storage.type.java`
- Angle brackets are inconsistently scoped, either as
    - keyword.operator.comparison.java
    - keyword.operator.bitwise.java
    - punctuation.bracket.angle.java
- Fields are highlighted incorrectly/differently depending on access modifier
- See images below

![screen shot 2018-02-11 at 11 42 22](https://user-images.githubusercontent.com/31404215/36072494-c93b5820-0f20-11e8-85cd-bea9b6615360.png)

## Steps to reproduce:
1. Use built in Monokai color theme (or other colorful theme)
2. Set syntax to "Java"
3. Write _completely normal_ Java code or paste the following example code:
```Java
public class Main {
    // with/without access modifier:
    public
    Set<Map.Entry<K, V>> entrySet0;
    Set<Map.Entry<K, V>> entrySet1;

    public static void main(String[] args) {
        Set<Map.Entry<K, V>> entrySet0;
        Node<K, V> m = someNode;
        Node<K, V> first = (Node<K, V>) someValue;
    }

    public static void method() {
        final int MY_CONSTANT = 0;
        int a = MY_CONSTANT + 1;

        int A = 1, B = 2;
        boolean less = A < B;
    }
}
```

![screen shot 2018-02-11 at 11 43 23](https://user-images.githubusercontent.com/31404215/36072493-c9205dc2-0f20-11e8-922b-5326720179ee.png)

_Copied from original issue: Microsoft/vscode#43414_

**Comment by aeschli** [comment]
_From @H-C-H on February 12, 2018 8:16_

Here is the same code rendered in Sublime Text. Seems to get it right.

![screen shot 2018-02-12 at 09 14 43](https://user-images.githubusercontent.com/31404215/36087942-3edde264-0fd5-11e8-8a24-ba966ed251ae.png)

**Comment by aeschli** [comment]
@H-C-H FYI

**Comment by sadikovi** [comment]
Could you provide version of Atom and/or language-java package?

Highlighting works for me for the latest master branch: e47a652dba757276c02ccb2cd4cdb4bf6914b8a5.
Here is the screenshot:
<img width="401" alt="highlight" src="https://user-images.githubusercontent.com/7788766/36142370-c2e090f6-110c-11e8-8c07-5881bd20de4c.png">

> Variables/constants starting with a capital letter are scoped as storage.type.java

Yes, this is the problem highlighted in https://github.com/atom/language-java/issues/76.

The rest (angle brackets highlighting) should be highlighted correctly. Yes, there are inconsistency with scopes. Normal generic types are highlighted correctly with `punctuation.bracket.angle.java`. Example of `(Node<K, V>) someValue` uses `keyword.operator.comparison.java` for some weird reason - will have a look.

So it looks like there are 2 problems to me: 
- Capital letters variables (#76)
- Generic angle brackets have the wrong scope in situations like `something = (A<B>) value`.

Will try addressing the latter and see what we can do about capitalised variables.

**Comment by sadikovi** [comment]
ping @50Wliu

**Comment by aeschli** [comment]
It's with the current master of atom/language-java (7a42895)
Your evaluation makes sense.

**Comment by sadikovi** [comment]
Sorry, forgot to fetch upstream. Still the same highlighting as on image above - no random red angle brackets for Sets.

**Comment by sadikovi** [comment]
All good! Will try fixing it - thanks for reporting!

**Comment by sadikovi** [comment]
After the discussion on the maintainer chat I decided to close this issue, because it contains more than reported problem (3 actually) - see the comment above (https://github.com/atom/language-java/issues/127#issuecomment-365206976).

Instead, I have created and linked separate issues (created from this one), see all links above (issues 76, 131, 132). Will try addressing those as soon as I can. 

Please, refer to those issues if you have a specific information or want to help with fixing them. Thanks!

ping @50Wliu @lee-dohm.
