### ISSUE TITLE
Add Java 9/10 keywords

### ISSUE THREAD

**Issue by snjeza** [atom/language-java#142]
Java 9 introduces the following keywords:
open,module,requires,transitive,exports,opens,to,uses,provides and with

See §3.9 in http://cr.openjdk.java.net/~mr/jigsaw/spec/java-se-9-jls-diffs.pdf

It will enable module-info.java syntax highlighting.
See https://github.com/redhat-developer/vscode-java/issues/527

**Comment by sadikovi** [comment]
Fixed by #143
