### ISSUE TITLE
Field values are incorrectly highlighted

### ISSUE THREAD

**Issue by aeschli** [atom/language-java#158]
_From @rickyah on September 3, 2018 8:55_

Issue Type: <b>Bug</b>

Using this snippet makes any text written after the BUG_SAMPLE variable to render as a string:

```java
final class Example
{
    private static final String MODULE = "test"

    private static final String BUG_EXAMPLE = "window." + TEST + "aFunction();";

    Example(PopupWebView popupWebView)
    {
        this.popupWebView = popupWebView;
    }
}
```

Atom (language-java 0.30.0) highlights this correctly, but VSCode (on master) ends the variable declaration with the `=`.

![screenshot from 2018-09-12 15-56-25](https://user-images.githubusercontent.com/6461412/45429899-7cd49b00-b6a4-11e8-8f72-402351e6b809.png)
![screenshot from 2018-09-12 15-56-50](https://user-images.githubusercontent.com/6461412/45429902-7e05c800-b6a4-11e8-9731-bcfe78808921.png)

**Comment by aeschli** [comment]
Sorry, I was too fast. Works in Atom. Will investigate on the VSCode side

**Comment by aeschli** [comment]
Found it. The problem is with change https://github.com/atom/language-java/commit/2f20bc5a5b07686ec0139e2969431210d81b6991#diff-854de79c7abc9c505592fcddfc4654f9

The matching of `=` got removed, so now the `=` is consumed by the end rule.
Not sure why Atom doesn't show the problem.

I suggest to fix this by adding  `'applyEndPatternLast': 1` to the `variable` rule

**Comment by sadikovi** [comment]
This is not a bug, we explicitly changed variable declaration to end with `=` in case of `int a = 123;` and with `;` in case of `int a;`. See https://github.com/atom/language-java/pull/146.
