### ISSUE TITLE
Array initializer recognized as inner class

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#172]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```java
class A {
    public void getParamToIntArray(String key) {
        Integer.valueOf(string.trim());
        new Integer[] { Integer.valueOf(string.trim()) };
    }
}
```

![image](https://user-images.githubusercontent.com/2417391/48907222-c3632480-eea1-11e8-9168-4975eaa62fcb.png)

Screenshot taken in VSCode using java.cson from version  d48e7137f6634cc094f092b68e6b110f51f47630.

### Steps to Reproduce

1. Open new tab and select Java language.
2. Paste code into the editor.

**Expected behavior:** [What you expect to happen]

The two `Integer`s should have the same color and same scopes.

**Actual behavior:** [What actually happens]

Everything inside the array initializer is recognized in `meta.inner-class.java` scope.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sadikovi** [comment]
Good catch! It looks like `begin` of `meta.inner-class.java` is not exactly correct, only works when there are no spaces between square bracket and curly one. Anyway, will try fixing.

**Comment by felixhao28** [comment]
Not quire sure if this is a good fix: https://github.com/felixhao28/language-java/commit/46aaaac65ed780476a7f9327379200f2f6331842. FYI.

**Comment by sadikovi** [comment]
Thanks for the help! Yes, I am not sure either. I will run more tests, see
if your fix works. Otherwise, will have to come up with something else.

**Comment by Eskibear** [comment]
@sadikovi  any updates?
