### ISSUE TITLE
Overrided methods in enum is not highlighted properly

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#173]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Overrided methods in enum is not highlighted properly.

```java
enum TYPES {

    TYPE_A {
        @Override
        int f() {
            return 1;
        }
    }
    , TYPE_B {
        @Override
        int f() {
            return 2;
        }
    }, TYPE_DEFAULT;

    public int f() {
        return 0;
    }
}
```
![image](https://user-images.githubusercontent.com/2417391/48931775-09b49400-ef33-11e8-8927-98be14ac6d23.png)

### Steps to Reproduce

1. Open new tab and select Java language.
2. Paste code into the editor.

**Expected behavior:** [What you expect to happen]

TYPE_A, TYPE_B and TYPE_DEFAULT should have the same scopes.

the three definitions of `f` should have proper highlight.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sadikovi** [comment]
Yes, we don't support that syntax explicitly. Will try adding it, thanks.

**Comment by felixhao28** [comment]
For your reference, I made a quick fix here to unblock my current work: https://github.com/felixhao28/language-java/commit/ea26a493db7c7e7d07ea926f5c935689bfe44895

I will leave the test case to you.
