### ISSUE TITLE
Wrong highlighting in member-variables

### ISSUE THREAD

**Issue by snjeza** [atom/language-java#176]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=?&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Wrong highlighting in member-variables

### Steps to Reproduce

1. Open the following class in VS Code or Atom

```
public class Bath {
    private String // Initializing at point Definition
    s1 = "Happy";
    public String /**  Initializing at point Definition */
    s2 = "Happy";
}
```

**Expected behavior:**
![after](https://user-images.githubusercontent.com/388609/49037429-7a211680-f1ba-11e8-80c7-93135b56b7c4.png)

**Actual behavior:** 
![before](https://user-images.githubusercontent.com/388609/49037447-84dbab80-f1ba-11e8-95bf-c3a316a4d234.png)

**Reproduces how often:** 100%

### Versions

Atom    : 1.27.2
VS Code : 0.29.1
VSCode Java: 0.34.0

### Additional Information

Related issues: 
#169 
https://github.com/redhat-developer/vscode-java/issues/707

**Comment by Vigilans** [comment]
Current behavior:

![image](https://user-images.githubusercontent.com/20227484/69548947-4f3aef80-0fd3-11ea-82bc-34b411ba6897.png)

**Comment by sadikovi** [comment]
Relates to https://github.com/atom/language-java/issues/186. Closing as "not an issue".
