### ISSUE TITLE
`new` keyword messes with ternary operator when used in condition

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#179]
### Description

```java
public class A {
    void f() {
        String sex = new Random().nextInt(2) == 0 ? "female" : "male";
        String sex = new Random().nextInt(2) ? "female" : "male";
        String sex = Random().nextInt(2) ? "female" : "male";
        String sex = new Random() ? "female" : "male";
    }
}
```
![image](https://user-images.githubusercontent.com/2417391/49365411-ad672680-f721-11e8-9cb2-5a08e34c8fa0.png)

**Expected behavior:** [What you expect to happen]

The first string in "true branch" should be recognized as `string.quoted.double.java`, like in the third line.

**Comment by sadikovi** [comment]
Can you include the language-java version that you are testing against?

**Comment by felixhao28** [comment]
d48e7137f6634cc094f092b68e6b110f51f47630
