### ISSUE TITLE
Function call + array accessor + new operator introduces extra meta.function-call.java scopes

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#180]
### Description

```java
public class A {
    void f() {
        int a = 1;
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        g(education[new Random()]);
        int a = 1;
    }

    void g(Object o) {
        int a = 1;
    }
}
```

![image](https://user-images.githubusercontent.com/2417391/49366469-6169b100-f724-11e8-8f3a-c4e91b137fb0.png)

**Expected behavior:** [What you expect to happen]

As you can see, although the highlight is still correct, there are more `meta.function-call.java` than we need.

**Comment by sadikovi** [comment]
Can you include the language-java version that you are testing against?

**Comment by felixhao28** [comment]
d48e7137f6634cc094f092b68e6b110f51f47630
