### ISSUE TITLE
Missing scopes on brackets and parentheses

### ISSUE THREAD

**Issue by chbk** [atom/language-java#19]
Brackets and parentheses aren't scoped, they are the same color as variables:

![javab](https://cloud.githubusercontent.com/assets/7478535/9699187/a14dde0a-53d9-11e5-9b1d-b6f3d768dd2f.png)
```java
list[i] = (sum == n ? true : false);
```

Sometimes they can be distinguished in an identifier class: 

![javag](https://cloud.githubusercontent.com/assets/7478535/9699188/a47be748-53d9-11e5-8211-58c9271fe11e.png)
```java
public static void main(String[] args) {

}
```

But they still aren't scoped:

![javac](https://cloud.githubusercontent.com/assets/7478535/9699237/5474e496-53db-11e5-8f84-05956c1fc8b6.png)

**Comment by 50Wliu** [comment]
I'm actually getting some different results for the bottom one:
![image](https://cloud.githubusercontent.com/assets/2766036/9777238/75f71f88-572f-11e5-976f-6baebfadca1b.png)

What version of Atom are you on?

**Comment by chbk** [comment]
I'm using Atom 1.0.11

You're right this is the full code to get the same result:

    public class MyClass {
        public static void main(String[] args) {}
    }
