### ISSUE TITLE
Inner annotation class not tokenized after some modifiers

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#191]
What looks like now:

![image](https://user-images.githubusercontent.com/2417391/51294945-34612b80-1a50-11e9-9297-c15b1053bb44.png)

What should look like:

![image](https://user-images.githubusercontent.com/2417391/51294979-62467000-1a50-11e9-9fed-56327266e9b4.png)

```java
class A {

    @interface Annotation1 {
        String value() default "Annotaion1";
    }

    static @interface Annotation1 {
        String value() default "Annotaion1";
    }

    public @interface Annotation2 {
        String value() default "Annotaion2";
    }

    public static @interface Annotation3 {
        String value() default "Annotaion3";
    }
}
```

A straight fix is to change [this line](https://github.com/atom/language-java/blob/master/grammars/java.cson#L811) to `'end': '(?=\\=|;|@interface)',`.

**Comment by sadikovi** [comment]
Okay, I will have a look. Thanks!

**Comment by sadikovi** [comment]
Fixed.
