### ISSUE TITLE
Minus operator confused with variable after new constructor

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#192]
Current behavior

![image](https://user-images.githubusercontent.com/2417391/51367518-efa7c400-1b25-11e9-8387-78d664310a8a.png)

Expected:

![image](https://user-images.githubusercontent.com/2417391/51367499-dd2d8a80-1b25-11e9-9dd3-c978d6140c7b.png)

Code:

```java
class A {
    void f() {
        int a = new Date().getTime() - start.getTime();
    }
}
```

Fix:

Change [this line](https://github.com/atom/language-java/blob/master/grammars/java.cson#L194) from 

```
'end': '(?=;|\\)|,|:|}|\\+)'
```

 to

```
'end': '(?=;|\\)|,|:|}|\\+|\\-)'
                           ^^^
```

**Comment by sadikovi** [comment]
I will check, thanks.
