### ISSUE TITLE
Underscore "_" not recognized inside type qualifier

### ISSUE THREAD

**Issue by felixhao28** [atom/language-java#198]
### Description

When a type qualifier starts with "_", it breaks the grammar for the rest of the line.

![image](https://user-images.githubusercontent.com/2417391/58155502-918f1700-7ca6-11e9-9a34-1e854f3a848f.png)

### Fix

I replaced all `[A-Za-z]\\w*` to `[a-zA-Z$_][\\.a-zA-Z0-9$_]*`, and `(\\w+\\.)*[A-Z]+\\w*` to `([a-zA-Z$_][a-zA-Z$_0-9]*\\.)*[A-Z]+\\w*)` it seems fixed.

**Comment by sadikovi** [comment]
Thanks. I will take a look.

**Comment by sadikovi** [comment]
@felixhao28 would you like to submit a patch? I am a bit snowed under at the moment, would appreciate if you could help out, plus, you seem to have fixed it already!

**Comment by felixhao28** [comment]
Although I have been a maintainer of several TextMate syntax-based plugins for a few years, I am still not confident messing with syntax files I am not familiar with.
