### ISSUE TITLE
Snippets not working for '.source.java' on .jsp files

### ISSUE THREAD

**Issue by mackelito** [atom/language-java#20]
in java.cson (using modular snippets plugin) 

    '.source.java':
      'Testing':
        'prefix': 'test'
        'body': 'test.testing'

this works fine in .java files but not in .jsp

**Comment by 50Wliu** [comment]
This is because `.jsp` files have the scope `.text.html.jsp`, not `.source.java`.  See https://github.com/atom/language-java/blob/master/grammars/java%20server%20pages%20(jsp).cson#L1.
