### ISSUE TITLE
Java variable-highlight

### ISSUE THREAD

**Issue by alexr00** [atom/language-java#202]
Original from @JoeyRxy in https://github.com/microsoft/vscode/issues/79108

```java
int x = 0, y = 0;
```
you will find the `y` doesn't be recognized as a variable.

When I use `TM scope inspector` to find what `y`'s kind is,it tells me `y` is a `meta.method.body.java` instead of `variable`(but `x` is `variable`).

And then I find when you type this:
```java
int x = 0, y = 0;
int z = x + y;
```
the `x` and `y` at second line isn't recognized as `variable` either.

Today I find more:
![bugs](https://github.com/JoeyRxy/tmp/blob/master/Snipaste_2019-08-15_13-36-53.png)
![bugs](https://github.com/JoeyRxy/tmp/blob/master/Snipaste_2019-08-15_13-37-33.png)
the array `BIT` has different scope in different place.

**Comment by JoeyRxy** [comment]
Can I modify the definition of `tm scope`?set `y` as `variable` too?

**Comment by sadikovi** [comment]
Feel free to open a PR to fix the issue!

**Comment by sadikovi** [comment]
We only implement variable declaration, we don't scope variables in assignments.

**Comment by sadikovi** [comment]
Relates to #178
