### ISSUE TITLE
Java scopes break when there are many Exceptions with a newline

### ISSUE THREAD

**Issue by alexr00** [atom/language-java#205]
From @JoeyRxy https://github.com/microsoft/vscode/issues/78445

Snippet. Notice that there is an newline in the catch clause between some exception types.
```java
public static void main(String[] args) {
	try {
		// something
	} catch (NoSuchMethodException | SecurityException | 
InstantiationException | llegalAccessException | IllegalArgumentException | invocationTargetException e) {
		e.printStackTrace();
	}
}
```

Only the last exception type on each line get the scope:
storage.type.java
meta.function-call.java
source.java

The other exception types get scope:
meta.function-call.java
source.java

**Comment by sadikovi** [comment]
Looks similar to this: #186
