### ISSUE TITLE
Catch parameter not correctly highlighted when declared in new line or with a comment in between

### ISSUE THREAD

**Issue by Vigilans** [atom/language-java#219]
### Description

Catch parameter name is highlighted as type when declared in new line or with a comment in between.

### Steps to Reproduce

Paste the following code to editor:

```java
public static void main(String[] args) {
    try {
        // something
    } catch // this is a comment
    (NoSuchMethodException |
        SecurityException
      | InstantiationException | llegalAccessException |
      IllegalArgumentException | invocationTargetException 
      e
    ) {
        e.printStackTrace();
    }
}

public static void main(String[] args) {
    try {
        // something
    } catch // this is a comment
    (NoSuchMethodException |
        SecurityException
      | InstantiationException | llegalAccessException |
      IllegalArgumentException | invocationTargetException /* comment */ e
    ) {
        e.printStackTrace();
    }
}
```

**Expected behavior:** `e` is highlighted as `variable.parameter.java`

**Actual behavior:** 

`e` is highlighted as `storage.type.java`:
![image](https://user-images.githubusercontent.com/20227484/70203053-a587fb00-1756-11ea-8543-1b89fe2f1a4e.png)

**Reproduces how often:** Always

**Comment by lkashef** [comment]
Hello @Vigilans, thanks for the report, I have simplified the examples, let me know if you have any comments.

Closing bracket in on a new line.

```
try {} catch (ex e
){}
```
Comment between the type and variable name.

```
try {} catch (ex /**/ e){}
```

**Comment by sadikovi** [comment]
It is basically two scenarios:
- there is a comment between `Exception` and `e` -> have to update regex
- `e` is on a new line -> oniguruma engine limitation (can't match new lines, see https://github.com/atom/language-java/issues/186)

**Comment by Vigilans** [comment]
@lkashef 
```
try {} catch (ex e
){}
```
should be 
```
try {} catch (ex
e){}
```

**Comment by lee-dohm** [comment]
Thanks @sadikovi! 🙇
