### ISSUE TITLE
Java 14's new record keyword is not highlighted properly

### ISSUE THREAD

**Issue by fbricon** [atom/language-java#223]
### Prerequisites
 * [ ]  Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
  * [ ] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
  * [ ] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
  * [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
  * [ ] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Java 14's new record keyword is not highlighted properly

### Steps to Reproduce

1. in a Java class, type `record Point(int x, int y){}`

**Expected behavior:**

record should be colored as a Java keyword, similar to class or interface

**Actual behavior:**

record looks meh
![record](https://user-images.githubusercontent.com/148698/76419032-f6377180-639f-11ea-8028-c4292b3813a5.png)

**Reproduces how often:**

100%

cc @Vigilans @akaroml

**Comment by sadikovi** [comment]
Can you link java documentation about `record` keyword? We just need to add it to the grammar, should be fairly easy to do.

**Comment by fbricon** [comment]
There: https://openjdk.java.net/jeps/359

**Comment by Eskibear** [comment]
#### Grammar
```
RecordDeclaration:
  {ClassModifier} record TypeIdentifier [TypeParameters] 
    (RecordComponents) [SuperInterfaces] [RecordBody]

RecordComponents:
  {RecordComponent {, RecordComponent}}

RecordComponent:
  {Annotation} UnannType Identifier

RecordBody:
  { {RecordBodyDeclaration} }

RecordBodyDeclaration:
  ClassBodyDeclaration
  RecordConstructorDeclaration

RecordConstructorDeclaration:
  {Annotation} {ConstructorModifier} [TypeParameters] SimpleTypeName
    [Throws] ConstructorBody
```

cited from the JEP above

**Comment by sadikovi** [comment]
We don't even support JDK 10 and 11 fully yet 😄. Feel free to open a pull request!

**Comment by Eskibear** [comment]
PR created.  Below is its looking in vscode. 

#### Before
![Screen Shot 2020-04-02 at 7 43 57 PM](https://user-images.githubusercontent.com/2351748/78245611-57bfab80-751a-11ea-953c-c48a5313bf21.png)


#### After
![Screen Shot 2020-04-02 at 7 36 47 PM](https://user-images.githubusercontent.com/2351748/78245074-5d68c180-7519-11ea-9bee-e6b093a58068.png)
