### ISSUE TITLE
Missing scopes for angle brackets and commas

### ISSUE THREAD

**Issue by chbk** [atom/language-java#23]
Angle brackets and commas aren't tokenized when used for generic type parameters:

![java1](https://cloud.githubusercontent.com/assets/7478535/10280510/026e5510-6b6e-11e5-9737-2ab5c5bd0433.png)

![html1](https://cloud.githubusercontent.com/assets/7478535/10280553/35fea09c-6b6e-11e5-8402-f55e90448c43.png)

![java3](https://cloud.githubusercontent.com/assets/7478535/10280990/af010d7e-6b71-11e5-8acd-e581fba041cd.png)

![html3](https://cloud.githubusercontent.com/assets/7478535/10280991/b4f375f0-6b71-11e5-9713-26ac7419267c.png)

**Comment by 50Wliu** [comment]
Question: what should the `T` in your second example be tokenized as?  Should it even have its own special token?

**Comment by chbk** [comment]
`T` stands for generic type, it's a placeholder for an actual class when instantiating `List`. IMO it should be tokenized the same way as `Integer` and `String` above.
