### ISSUE TITLE
Highlight keyword 'sealed' for Java 15

### ISSUE THREAD

**Issue by Eskibear** [atom/language-java#232]
See: [JEP 360](https://openjdk.java.net/jeps/360)

It's not yet highlighted. 
<img alt="Screen Shot 2020-09-16 at 12 24 31 PM" width="184" src="https://user-images.githubusercontent.com/148698/93325616-ddf55300-f817-11ea-97b2-14113fdf93cf.png">

**Comment by fbricon** [comment]
`permits`
<img width="321" alt="Screen Shot 2020-09-18 at 5 09 02 PM" src="https://user-images.githubusercontent.com/148698/93614216-20fb2600-f9d2-11ea-9d74-64c167364c92.png">
 and following classes also need to be supported

**Comment by sadikovi** [comment]
Can you provide java spec for those keywords?
