### ISSUE TITLE
Coloring is too BAD

### ISSUE THREAD

**Issue by ibocon** [atom/language-java#25]
In dark solarized theme & ubuntu 14.04,
Most color used in under source code is just blue!
Better colored source codes make users better to get into code.

``` java
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class Application implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    public static void main(String args[]) {
        SpringApplication.run(Application.class);
    }

    @Override
    public void run(String... strings) throws Exception {
        RestTemplate restTemplate = new RestTemplate();
        Quote quote = restTemplate.getForObject("http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
        log.info(quote.toString());
    }
}

```
To be specific,

in function signature,
```
scope returnType functionName (arguments)
````
are just blue color.

even import are all colored blue..
```
import pakagePath.function
```
make pakagePath and Function should be colored differently for user interface.

Even, className is colored blue.

Therefore, I suggest to change coloring policy for Java source code.

**Comment by thomasjo** [comment]
This is not a problem with the language grammar, but rather something that needs to be addressed in the [solarized-dark](https://github.com/atom/solarized-dark-syntax) theme, so please re-open the issue there.

**Comment by ibocon** [comment]
![report](https://cloud.githubusercontent.com/assets/9730869/10902394/d520bbb4-81c2-11e5-9e62-f788c953beeb.png)

Sorry for late report.

So, as you can see on the picture,
 'function' name is not distinguishable well.
'Exception' is also blue.
