### ISSUE TITLE
Constructor reference breaks syntax highlighting

### ISSUE THREAD

**Issue by ghost** [atom/language-java#28]
Using a constructor reference within a code block in .rst or .md files breaks syntax highlighting for everything after that code block. I do believe this is an issue with the java grammar, as I was able to reproduce it with both of the aforementioned languages.

A screenshot showing the faulty highlighting in a java code block within a .rst file can be found [here](https://camo.githubusercontent.com/b8b9659efa5ee954fd35b223bf4dfe1835ccd1d9/687474703a2f2f692e696d6775722e636f6d2f554854704470352e706e67).

The error only occurs on constructor references (`SomeClass::new`), normal method references (`SomeClass::someMethod`) work fine.

**Comment by saladoc** [comment]
After taking a closer look it seems that (method references)[https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.13] are not recognised by the grammar yet.

**Comment by sadikovi** [comment]
Tested in markdown, no syntax breakage like in the image.
