### ISSUE TITLE
Implementing Type with Type parameter as Array highlights weird

### ISSUE THREAD

**Issue by ryanr1230** [atom/language-java#29]
implementing a Type with an array as the type parameter does not highlight correctly (e.g., "class A implements B\<C\[\]\> " -- shown below)

<img width="377" alt="This looks strange" src="https://cloud.githubusercontent.com/assets/667391/11857649/d1145d8a-a41f-11e5-8a57-2c12c3abb18d.png">

**Comment by 50Wliu** [comment]
Will hopefully get fixed by #22.
