### ISSUE TITLE
Highlighting issue with 'instanceof' keyword

### ISSUE THREAD

**Issue by joemcadams** [atom/language-java#31]
I've found that the instanceof keyword is not highlighted as an operator (see line 506 in master/grammars/java.cson). Anyone else have this issue?

![instanceofbug](https://cloud.githubusercontent.com/assets/10790010/13651512/456ab7cc-e60d-11e5-8685-e1db254cddfd.png)

**Comment by 50Wliu** [comment]
I cannot reproduce this using language-java@0.18.0; assuming fixed.
