### ISSUE TITLE
Qualified instance variables are not highlighted

### ISSUE THREAD

**Issue by 50Wliu** [atom/language-java#47]
EDIT: see https://github.com/atom/language-java/issues/47#issuecomment-264060903
![qualified-no-highlight](https://cloud.githubusercontent.com/assets/2766036/15911740/0cc1e1e6-2d9f-11e6-82a7-308f685d8ad9.png)
vs
![variable-highlighting](https://cloud.githubusercontent.com/assets/2766036/15911816/68e66c44-2d9f-11e6-8409-2acb60151aa8.png)

``` java
class A
{
    private Test.Double something; // Double is tagged as `variable.other.property.java`
    private Double something2;
}
```

**Comment by noseglid** [comment]
I also noted that generics are not scoped properly unless they have a visibility modifier. Could it be the same issue?
![screen shot 2016-06-09 at 8 30 53 am](https://cloud.githubusercontent.com/assets/933880/15920724/93cde338-2e1c-11e6-8db5-1a0b1f016040.png)

**Comment by 50Wliu** [comment]
Possibly!

**Comment by 50Wliu** [comment]
@noseglid this actually just got worse with #53:
![even-worse](https://cloud.githubusercontent.com/assets/2766036/15994720/ea98be26-30d9-11e6-8184-41029dc69bfb.png)

**Comment by 50Wliu** [comment]
Something else:
![partial-highlighting](https://cloud.githubusercontent.com/assets/2766036/15994813/8cfb29e0-30dc-11e6-8ecf-6359f9634d0e.png)

**Comment by noseglid** [comment]
Both comments addresses in #58

**Comment by 50Wliu** [comment]
This is getting better.
![qualified-better-highlighting](https://cloud.githubusercontent.com/assets/2766036/20779589/70783018-b743-11e6-88e0-e348e81916fc.png)
`Double` just needs to be tokenized properly now.
