### ISSUE TITLE
There's nothing identifying catch blocks

### ISSUE THREAD

**Issue by noseglid** [atom/language-java#48]
There's no scopes set on stuff in catch blocks. See this simple example:
```java
class MyClass {
  public static void main(String[] args) {
    try {
    } catch (Exception exception) {
    }
  }
}
```
![screen shot 2016-06-09 at 18 26 15](https://cloud.githubusercontent.com/assets/933880/15937570/c5462a4e-2e6f-11e6-81da-77ea1f7a2ab8.png)

I would find it beneficial if there were a scope set on everything within the parenthesis (`Exception`, ` ` and `exception` in my example). What would that scope be called?

**Comment by 50Wliu** [comment]
I'm not really good at naming these things - @MaximSokolov any ideas?

Something that comes to mind though is `meta.catch-exception.java`.

**Comment by MaximSokolov** [comment]
`Exception` – `storage.type.exception`
`exception` – `variable.other.exception` (not sure, maybe `entity.other.exception`?)
The whole block could be scoped as `meta.catch-exception`, though I don't think it is necessary. Whitespaces shouldn't be scoped.

Ref: [TextMate naming conventions](http://manual.macromates.com/en/language_grammars#naming_conventions)
