### ISSUE TITLE
Array variable declarations are not highlighted

### ISSUE THREAD

**Issue by 50Wliu** [atom/language-java#50]
![array-no-highlighting](https://cloud.githubusercontent.com/assets/2766036/15965870/5a1e0906-2eee-11e6-9f79-a333a0091a29.png)

```java
class A
{
    private int array[];
}
```

**Comment by noseglid** [comment]
I can give this a go. Been meaning to rewrite the variable structure.

I suppose your example is missing storage type?
```java
class A
{
    private int array[];
}
```

Regarding the variable structure, I want to split it into two separate categories. One (called something like `member-fields`) will match storage modifers and such (`private`, `protected`, `static`, etc). It will then include the `variables` structure (which match variables as they are matched today, but without modifiers).

**Comment by 50Wliu** [comment]
> I suppose your example is missing storage type?

Oops, fixed! :see_no_evil: 

Your new structure sounds like a good idea.
