### ISSUE TITLE
instanceof keyword not highlighted

### ISSUE THREAD

**Issue by ShanTulshi** [atom/language-java#52]
![image](https://cloud.githubusercontent.com/assets/6186771/15976933/95c69966-2f0a-11e6-8152-5d730ea04a09.png)

**Comment by 50Wliu** [comment]
`instanceof` tokenizes correctly for me - you may want to report this over at [atom/one-light-syntax](https://github.com/atom/one-light-syntax) (or whatever syntax theme you're using).

**Comment by noseglid** [comment]
It gets the scope `keyword.operator.instanceof.java` for me too, which is correct.

[atom/one-dark-syntax](https://github.com/atom/one-dark-syntax) doesn't highlight it either.
