### ISSUE TITLE
Support highlighting for javadoc

### ISSUE THREAD

**Issue by sadikovi** [atom/language-java#54]
Currently, as of version 0.17.0 of the package, there is no javadoc highlight. I could not find option to enable it either. What do you think about adding this feature? Or have you considered adding it in the past? For example, `language-scala` supports highlighting, so we could just implement something very similar, I guess.

@50Wliu I would appreciate your feedback on this, thanks.

**Comment by 50Wliu** [comment]
I'm definitely :+1: on adding javadoc support.

**Comment by sadikovi** [comment]
PR has been merged, I will close it.
