### ISSUE TITLE
Doesn't gray out comment blocks inside method/constructor parameter list

### ISSUE THREAD

**Issue by awvalenti** [atom/language-java#60]
This snippet works correctly (comment is grayed out):
```(/* comment */)```

This one does not (comment is not grayed out):
```method(/* comment */)```

Full example with bug:
```public Constructor(String p1, String p2/*, String p3*/)```

Full example without bug:
```public (String p1, String p2/*, String p3*/)```

**Comment by sadikovi** [comment]
@50Wliu can you mark it as bug as well, please?
