### ISSUE TITLE
syntax coloring is broken for some floating point constants

### ISSUE THREAD

**Issue by unreasonableman** [atom/language-java#69]
Hi,

java syntax coloring breaks for some floating point constants:

```java
float foo = 0.1f; // okay
float bar = .1f; // not okay
```

The latter case leads to '1f' being highlighted in bright red.

Pic attached to illustrate the issue.

![atom-syntax](https://cloud.githubusercontent.com/assets/833549/20774327/bc6f9e18-b70a-11e6-8c3c-b6339107d5b4.png)

**Comment by 50Wliu** [comment]
Thanks for the issue @unreasonableman!

**Comment by 50Wliu** [comment]
Ok, I have a fix at #70.  If you want to test it out you can check it out using Git and then `apm link` it.  Make sure not to forget to unlink it though after an Atom version is released that contains the fix.
