### ISSUE TITLE
Support default keyword

### ISSUE THREAD

**Issue by saadq** [atom/language-java#71]
I'm trying to add syntax highlighting to the `default` word in code like this:

```java
public interface Lion {
    default void roar() {
        // roar
    }
}
```

However, the only selectors available seem to be `.meta.method.return-type`. Is there any plan to add Java 8 stuff like this and maybe add the `default` word to something like `.storage.modifier` or something?

**Comment by 50Wliu** [comment]
PRs will definitely be merged, however I don't have enough experience with Java 8 to try adding the keywords myself without potentially naming them wrong/misunderstanding how things work.
