### ISSUE TITLE
Try-with-resources not colored

### ISSUE THREAD

**Issue by MisterDA** [atom/language-java#79]
### Description

Hello, I noticed that [Try-With-Resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) statements are not colored.
![screenshot-0](https://cloud.githubusercontent.com/assets/1773581/23126403/c2994724-f776-11e6-8e00-3e814b21dfe0.jpg)

**Expected behavior:** You would expect them to be colored just as regular Java code.

**Reproduces how often:** Always

### Versions

```
➜  ~ atom --version
Atom    : 1.14.3
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
➜  ~ apm --version
apm  1.15.2
npm  4.2.0
node 7.5.0 x64
python 3.6.0
git 2.11.1
➜  ~ uname -a
Arch Linux 4.9.8-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
```

Thank you !

**Comment by 50Wliu** [comment]
Thanks for reporting @MisterDA!

**Comment by 50Wliu** [comment]
Also, I noticed that you are running an unofficial distribution of Atom.  We generally do not offer support for unofficial distributions - I would highly suggest that you uninstall it as soon as possible and reinstall from https://atom.io.  You can read [the decision](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md) for why we chose not to support unofficial distributions, and subscribe for updates at https://bugs.archlinux.org/task/50357.

**Comment by MisterDA** [comment]
Hi, I tried the official version. I uninstalled [atom](https://www.archlinux.org/packages/community/x86_64/atom/) from the official repository and used the AUR package [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin) which uses the distribution from [atom.io](https://atom.io/). The problem remains on this version.
*I have not tested your fixes.*

Oddly, a friend of mine running an outdated version of Atom does not experience the problem. He has:
```
% atom --version
Atom    : 1.11.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
% apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
% uname -a
Linux 4.4.0-63-generic #84-Ubuntu 16.04 SMP 86_64 GNU/Linux
```

I have the `0.25.0` version of language-java and he has the `0.23.0`.

BTW, the conclusion of the Arch Linux bug thread [FS#50357](https://bugs.archlinux.org/task/50357) is that the developers are wrong and Arch Linux will not provide the official bundled Atom but externalize its dependencies.

**Comment by 50Wliu** [comment]
Yes, we've been making language-java more modular recently (before it would apply basic highlighting everywhere - now it tries to be smarter).  Of course, during that restructure, we didn't think about try-with-resources, which is probably why it regressed.

And yes, I've seen the conclusion of the linked Arch issue, which I strongly disagree with.  Almost every time they decide to upgrade to a new minor Electron version, we get a spate of mysterious bug reports about Atom not working (anywhere from "I can't open files" to "International keyboard support is broken").  This isn't really the place to discuss that though, but I would be happy to explain/discuss more if you post on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or [Slack](http://atom-slack.herokuapp.com/) (I'm `@wliu` on both of those platforms).
