### ISSUE TITLE
Resources part of the try-with-resources statement does falsely require a trailing semicolon

### ISSUE THREAD

**Issue by MoritzKn** [atom/language-java#88]
### Description

The resources part of the try-with-resources statement does falsely require a trailing semicolon.

### Steps to Reproduce

1. Open new file
2. Enter:
```java
class Main {
    public static void main() {
        try (Foo foo = bar) {
            
        }
    }
}
```

**Expected behavior:**
The `meta.try.resources.java` scope ends at the closing parenthesis and the try body gets the scope `meta.try.body.java`.

**Actual behavior:**
The `meta.try.resources.java` scope does never end and the try body still has the scopes `meta.try.resources.java` and `meta.definition.variable.java`.

**Reproduces how often:**
100%

### Versions
Reproduced in:
```
$atom --version 
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
(build from source)

With language-java at  `0.27.0` and in `master` (i.e. 7b4c32a4).

```
$ uname -a
Linux arch-pc 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux
```

### Other issues

Support for try-with-resources was originally added in #80 after being reported in #79.

### Additional Information

The Java Spec defines the syntax of this language element as:
```
TryWithResourcesStatement:
    try ResourceSpecification Block [Catches] [Finally]
ResourceSpecification:
    ( ResourceList [;] )
ResourceList:
    Resource {; Resource}
Resource:
    {VariableModifier} UnannType VariableDeclaratorId = Expression
```
See: http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3

Therefore the semicolon after the "ResourceList" is optional. Furthermore the resources in the try-with-resources can't be arbitrarily code (link it is currently the case), but have to be a special kind of assignment.

Relevant source code: [grammars/java.cson L532](https://github.com/atom/language-java/blob/7b4c32a4c97fa2a01eaaa2ae08a085ee08bba8fb/grammars/java.cson#L532)

I would fix it myself but I have no time at the moment + few experience with atom grammars, but maybe i have some time to look into it in the future.

**Comment by 50Wliu** [comment]
The best way to implement this is to create a separate rule for try-with-resources, because currently the [variable assignment rule](https://github.com/atom/language-java/blob/7b4c32a4c97fa2a01eaaa2ae08a085ee08bba8fb/grammars/java.cson#L1195) waits for the ending semicolon before terminating.

**Comment by MoritzKn** [comment]
Yeah, it isn't a normal assignment any way.
Normal assignment looks like this:
```
AssignmentExpression:
  ConditionalExpression 
  Assignment
Assignment:
  LeftHandSide AssignmentOperator Expression
LeftHandSide:
  ExpressionName 
  FieldAccess 
  ArrayAccess
AssignmentOperator:
  (one of)  =  *=  /=  %=  +=  -=  <<=  >>=  >>>=  &=  ^=  |=
```
The "Resource" from the try-with-resources statement dosen't support komplex assignments (`+=` etc.) for example.

**Comment by 11684** [comment]
I found a hacky workaround: adding a semicolon before the closing parenthesis of the try. It is redundant there, but it fixes the highlighting of the succeeding code.

**Comment by sadikovi** [comment]
Thanks for workaround! I managed to patch code for it to work:
```diff
diff --git a/grammars/java.cson b/grammars/java.cson
index 7c20d99..75bc3bf 100644
--- a/grammars/java.cson
+++ b/grammars/java.cson
@@ -1199,7 +1199,7 @@
         \\s*(=|;)
       )
     '''
-    'end': '(?=;)'
+    'end': '(?=;|\\))'
     'name': 'meta.definition.variable.java'
     'patterns': [
       {
@@ -1216,7 +1216,7 @@
         'beginCaptures':
           '0':
             'name': 'keyword.operator.assignment.java'
-        'end': '(?=;)'
+        'end': '(?=;|\\))'
         'patterns': [
           {
             'include': '#code'
```

This is hacky as well, however passes all tests in master branch.

**Comment by sadikovi** [comment]
I think it sort of relates to https://github.com/atom/language-java/issues/76. For example, this code renders just fine:
```java
class Main {
  public static void main() {
    try (foo = bar) {
          
    }
  }
}
```

It also looks like it forces class name with uppercase... Will try addressing this issue.

**Comment by garyrussell** [comment]
Are there any plans to merge this or fix the problem some other way?

**Comment by sadikovi** [comment]
There is an open pull request to fix this issue, but it needs to be revisited and rebased. Will get back to it soon.
